import { CULTS } from "@/lib/cults";
import { MARKET_ROOT, SERVICES } from "./catalog";

// Every real game page has a stable code; query strings do not change it.
export const GAME_PAGES = [
  "/",
  "/hidden-wiki-2",
  ...[
    "moneytasks",
    "moneytasks/services",
    "moneytasks/puzzels",
    "moneytasks/trivia",
    "red-room",
    "red-room/full-truth",
    "red-room/donors",
    "red-room/chat-replay",
    "red-room/signal-log",
    "leaks",
    "leaks/docs",
    "leaks/archive",
    "leaks/vehicles",
    "leaks/cards",
    "leaks/passwords",
    "cult",
    "cult/operators",
    "cult/chat-system",
    "cult/doctrine",
    "cult/ritual",
    "cult/status",
    "cult/forum",
    "events",
    "events/calendar",
    "events/albums",
    "events/guestbook",
    "events/tickets",
    "events/venues",
    "forum",
    "forum/threads",
    "forum/confessions",
    "forum/deadletters",
    "trace-node",
    "trace-node/terminal",
    "trace-node/nodes",
    "trace-node/trace",
    "trace-node/output",
    "trace-node/verification",
  ].map((path) => `/hidden-wiki-2/${path}`),
  ...CULTS.map((cult) => `/hidden-wiki-2/cult/${cult.slug}`),
  ...["", "/services", "/inbox", "/policy", "/weapons", "/substances"].map(
    (path) => MARKET_ROOT + path,
  ),
  ...SERVICES.map((service) => `${MARKET_ROOT}/services/${service.id}`),
];
